server:
  port: 7000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defautZone: http://localhost:7000/eureka/
  server:
    enable-self-preservation: false